name: null                          # Our env was made with --prefix
channels:
  - conda-forge                     # We added a third party channel
  - defaults
dependencies:
  - pip=19.3.1=py37_0
  - pip:                            # Packages installed from PyPI
    - molecules>=0.0.3.2
    - ParmEd==3.2.0
    - simtk.unit==0.2
    - click==7.0
    - pycodestyle==2.5.0
    - pydocstyle==4.0.1
    - pylint==2.3.1
    - pytest==5.1.2
    - -e .
